### ISSUE TITLE
a context change does nothing

### ISSUE THREAD

**Issue by jdewit** [transifex/transifex-delivery#73]
I'm just testing the cds api and I am noticing that when posting to /content, a change in a resource strings 'context' field does not end up changing anything. It shows as skipped.

**Comment by nbasili** [comment]
The context field cannot be altered after string creation, as it contributes to creation of the `resource_string_id` unique identifier of a string. You can see the relevant answer here as well: https://github.com/transifex/transifex-delivery/issues/75

**Comment by jdewit** [comment]
yeah, just noticed the v3 api also does not allow 'context' in the patch payload. This is fine. I can work around this.
