### ISSUE TITLE
a change in 'occurrences' does nothing

### ISSUE THREAD

**Issue by jdewit** [transifex/transifex-delivery#74]
I'm just testing the cds api and I am noticing that when posting to /content, a change in a resource strings 'occurrences' field does not end up changing anything. It shows as skipped.

**Comment by nbasili** [comment]
PATCHing over the occurrences field is not supported in APIv3 as you can see here: https://developers.transifex.com/reference/patch_resource-strings-resource-string-id

For this features to be supported (which sounds legitimate btw), it should be enabled in APIv3 first.

**Comment by jdewit** [comment]
this is would indeed be a nice feature. I was thinking about using this field to provide the filepath where the translation resides, or perhaps even the url where it can be found. If the file were to be renamed or moved, it would mean the only way to update would be to delete and create a new resource. Same goes for 'developer_comment'

**Comment by nbasili** [comment]
An update is on it's way.

**Comment by nbasili** [comment]
@jdewit CDS 4.0.0 was released today. By default occurrences will be appended to the existing string occurrences, unless the `override_occurrences` is set to true in the request.

Also, updating `developer_comment` of an existing string was already supported in previous versions.
