### ISSUE TITLE
context is not considered in the uniqueness of a resourceString

### ISSUE THREAD

**Issue by jdewit** [transifex/transifex-delivery#75]
when posting to /content, 

if i try posting a resource string to the CDS that has a 'key' that already exists in transifex but has a different 'context', it is rejected due to it not being unique.

However, when I try this against the v3 api, it does work, and creates a new resourceString.

The api docs make it sound like the v3 behavior is correct. 

"The identifier of the resource string in it's container. In cases where two resource strings in the same container share the same key, context is also used to disambiguate the identity of each resource string."

**Comment by nbasili** [comment]
This is kind of expected. When you create a new string using APIv3, a `resource_string_id` is created by hashing the key and the context attributes. So when you create a string with key A it will create a hash such as `hash(A)`. And when you push a string with key A and context B, it will create a hash such as `hash(A + B)`. So these two strings are identified separately in the scope of the API and Transifex itself.

This will work with Native SDKs out of the box, when the keys are generated automatically. For example:
`<T _str="Hello" />` will generate a key `Hello`.

while `<T _str="Hello" _context="homepage" />` will generate the key `Hello::homepage`. And this will work fine.

But if you define custom keys, such as:
`<T _str="Hello" _key="A" />`
`<T _str="Hello" _context="homepage" _key="A" />`
the key in both cases will be `A`, and Native cannot decide which one to pick, thus issue.

So given that you provide custom keys, you should also manually create unique keys as well.

**Comment by jdewit** [comment]
Hmm, I don't understand what the Native SDK's have to do with this. I see this as a bug in the CDS '/content' endpoint. Let me try explaining this a little more clearly.

a POST request to https://rest.api.transifex.com/resource_strings with payload:

`{
    "data": [
        {
            "attributes": {
                "context": "c1",
                "key": "k1",
                "strings": {
                    "other": "Test"
                },
                "tags": [
                    "tag1"
                ],
                "developer_comment": "",
                "occurrences": "some-place.html"
            },`

followed by another request 

`{
    "data": [
        {
            "attributes": {
                "context": "c2",
                "key": "k1",
                "strings": {
                    "other": "Test"
                },
                "tags": [
                    "tag1"
                ],
                "developer_comment": "",
                "occurrences": "some-place.html"
            },`

**creates 2 resources.**

Contrary to a POST request to https://cds.svc.transifex.net/content with

`{
    "data": {
        "key1": {
            "string": "some str",
            "meta": {
              "tags": ["t1"],
              "context": "context-1"
            }
        }
    }
}`

followed by another request

`{
    "data": {
        "key1": {
            "string": "some str",
            "meta": {
              "tags": ["t1"],
              "context": "context-2"
            }
        }
    }
}`

**creates 1 resource, 2nd one is 'skipped'.**

**Comment by nbasili** [comment]
CDS is not an 1-1 wrapper on top of APIv3. It is a service created to provide [Over-The-Air translations to the Native SDKs](https://developers.transifex.com/docs/content-delivery-service). It is part of the Transifex Native solution ecosystem. The SDKs cannot use the APIv3 directly, as there are rate limits, pagination, and other limitations that cannot be used for end-user delivery. This is where CDS comes in and full-fills that purpose. 

The Native SKDs have some design principles. In APIv3, the unique identifier of a string is a `hash`. In Native SDKs it is the  `key`. So it does not work exactly the same.

The equivalent `GET /content` request returns a response like:
```
{
  "data": {
     "key1": {
        "string": "some str"
    }
  }
}
```

Two different strings with the same `key` cannot represented in that response:
```
{
  "data": {
     "key1": {
        "string": "some str"
      }
    },
     "key1": {
        "string": "some str" (with the second context)
      }
    }
  }
}
```

The only way to achieve what you are looking for, is to POST the following:
```
{ "data": { "key1::context-1": { "string": "some str", "meta": { "tags": ["t1"], "context": "context-1" } } } }
```
followed by
```
{ "data": { "key1::context-2": { "string": "some str", "meta": { "tags": ["t1"], "context": "context-2" } } } }
```
